UM 10.8 updates
metomi/metomi-vms pull request #9
Opened 2017-06-20 10:12 UTC by paulcresswell

@dpmatthews Changes to the um-setup script that will be needed to run UM 10.8 on the VM, plus additional improvements for better error checking and to make it easier to use. Please review.

2017-06-21 08:14 UTC, dpmatthews approved these changes
Looks fine to me. Review requested from @scwhitehouse

2017-06-21 11:32 UTC, scwhitehouse requested changes
Nothing serious. One issue looks like a bug, one might be a bug but might also be me misunderstanding, and a couple of other things to consider.

I'm assuming this has been tested in on and off-line modes on the VM!

2017-06-21 11:32 UTC, scwhitehouse commented on usr/local/bin/um-setup
> +  if [[ $src =~ ^fcm:|^svn:|file: ]]; then
Do we have a requirement to support svn+ssh, http, etc?

2017-06-21 11:32 UTC, scwhitehouse commented on usr/local/bin/um-setup
> +  SHUM_OPENMP=$shum_omp make -f make/${vm_config}.mk shum_wgdos_packing &> "$install_dir/make.log"
I'm probably missing something, but is this saying that if ``shum_omp=false`` then you want to run ``false make -f ....``? Should it be ``$omp make -f ..." instead? (I can't remember how that gets built...)

2017-06-21 11:32 UTC, scwhitehouse commented on usr/local/bin/um-setup
> +  echo "Cannot find a GCOM build in $cdir"
``$gdir`` instead of ``$cdir``?

2017-06-21 11:32 UTC, scwhitehouse commented on usr/local/bin/um-setup
> +  if ! grep -qL "location{primary}\[$keyword\]" $keyfile; then
This doesn't check that the keyword is set to the correct path, I think, just that it exists? (Unlike the rose.conf rose-ana database test later which does check that it's true).

2017-06-21 11:37 UTC, scwhitehouse commented on usr/local/bin/um-setup
> +  if [[ $src =~ ^fcm:|^svn:|file: ]]; then
I should add that "no" is perfectly acceptable as an answer from my point of view!

2017-06-23 07:06 UTC, scwhitehouse approved these changes
Those changes look fine to me!

2017-06-23 07:14 UTC, scwhitehouse commented on usr/local/bin/um-setup
> +  SHUM_OPENMP=$shum_omp make -f make/${vm_config}.mk shum_wgdos_packing &> "$install_dir/make.log"
For future reference, I was missing something... this sets $SHUM_OPENMP=true (or false) before invoking make, and that's what Shumlib's make file requires...

2017-06-23 07:14 UTC, scwhitehouse commented on usr/local/bin/um-setup
> +  echo "Cannot find a GCOM build in $cdir"
My mistake. Oops.

2017-06-23 07:20 UTC, merged